-   id: detect-secrets
    name: Detect secrets
    description: Detects high entropy strings that are likely to be passwords.
    entry: run-scan.sh
    language: python
    # for backward compatibility
    files: .*
