language: python
env:
    - TOXENV=py27
matrix:
    include:
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=pypy
          python: pypy
install:
    - pip install tox
script: make test
cache:
    directories:
        - $HOME/.cache/pre-commit
